main:
	gcc -o readfile main.c
	./readfile
	./readfile main.c
clear:
	rm -rf readfile
test:
	gcc -o readfile main.c
	./readfile
	./readfile main.c
	./readfile dfghjfreghwofwj
	./readfile 0ewdghedf	giuew
	./readfile Makefile
	rm -rf readfile